using DairyManagement.Application.Abstractions;
using DairyManagement.Domain.BatchRawMaterial;

namespace DairyManagement.Application.Production.Repositories;

public interface IBatchRawMaterialRepository:IBaseRepository<BatchRawMaterial>;