using DairyManagement.Application.Abstractions;
using DairyManagement.Domain.ProductionStageRecord;

namespace DairyManagement.Application.Production.Repositories;

public interface IProductionStageRecordRepository :IBaseRepository<ProductionStageRecord>;